[package]
name = "gdcf_dbcache"
version = "0.1.0"

[dependencies]
diesel = "^1.2.2"

[dependencies.gdcf]
path = "../gdcf"

[features]
default = []

postgres = ["diesel/postgres"]
mysql = ["diesel/mysql"]
sqlite = ["diesel/sqlite"]