[package]
name = "gdcf_dbcache"
version = "0.1.0"

[dependencies]
diesel = "^1.2.2"
chrono = "^0.4.0"

[dependencies.gdcf]
path = "../gdcf"

[features]
default = []

postgres = ["diesel/postgres", "diesel/chrono"]
mysql = ["diesel/mysql", "diesel/chrono"]
sqlite = ["diesel/sqlite", "diesel/chrono"]