[package]
name = "gdcf"
version = "0.1.0"

[dependencies]
futures = "^0.1.17"
tokio-core = "0.1"
serde = "1.0"
serde_derive = "1.0"
gdcf_derive = { path = "../gdcf_derive" }
lazy_static = "1.0"

[features]
gj-format = []